import type { SkillGroup } from '@core/models';

export const SKILL_GROUPS: readonly SkillGroup[] = [
  {
    id: 'angular',
    title: 'Angular',
    icon: 'layers',
    emphasis: 'primary',
    caption: 'My main stack — v14 through v21, in production every working day.',
    skills: [
      { name: 'Angular v14 – v21', level: 'production' },
      { name: 'RxJS', level: 'production' },
      { name: 'NgRx', level: 'production' },
      { name: 'Reactive Forms', level: 'production' },
      { name: 'Router & Lazy Loading', level: 'production' },
      { name: 'OnPush Change Detection', level: 'production' },
      { name: 'Dependency Injection', level: 'production' },
      { name: 'HttpClient & Interceptors', level: 'production' },
      { name: 'SPA architecture', level: 'production' },
      { name: 'Angular CLI', level: 'production' },
      { name: 'Standalone Components', level: 'production' },
      { name: 'Signals', level: 'production' },
      { name: 'PrimeNG', level: 'strong' },
      { name: 'Zoneless', level: 'working' },
    ],
  },
  {
    id: 'javascript',
    title: 'JavaScript & TypeScript',
    icon: 'code',
    emphasis: 'primary',
    caption: 'The language layer underneath everything else on this page.',
    skills: [
      { name: 'TypeScript', level: 'production' },
      { name: 'JavaScript ES2015+', level: 'production' },
      { name: 'Promises & async / await', level: 'production' },
      { name: 'Classes & Modules', level: 'production' },
      { name: 'Optional chaining / nullish', level: 'production' },
      { name: 'Closures & Prototypes', level: 'strong' },
      { name: 'Generics & Utility Types', level: 'strong' },
      { name: 'Immutable data patterns', level: 'strong' },
    ],
  },
  {
    id: 'markup',
    title: 'HTML & CSS',
    icon: 'palette',
    emphasis: 'primary',
    caption: '50+ components that had to survive every browser the product supports.',
    skills: [
      { name: 'Semantic HTML5', level: 'production' },
      { name: 'CSS3', level: 'production' },
      { name: 'SCSS', level: 'production' },
      { name: 'BEM', level: 'production' },
      { name: 'Flexbox', level: 'production' },
      { name: 'CSS Grid', level: 'production' },
      { name: 'Mobile-first / Responsive', level: 'production' },
      { name: 'Cross-browser support', level: 'production' },
      { name: 'Tailwind CSS', level: 'production' },
      { name: 'SEO & structured data', level: 'strong' },
      { name: 'Accessibility (WCAG)', level: 'working' },
    ],
  },
  {
    id: 'backend',
    title: 'Backend & APIs',
    icon: 'terminal',
    emphasis: 'primary',
    caption: 'Enough to write the endpoint myself when waiting for it is the slower option.',
    skills: [
      { name: 'API integration', level: 'production' },
      { name: 'Postman', level: 'production' },
      { name: 'WebSockets', level: 'strong' },
      { name: 'Node.js', level: 'strong' },
      { name: 'NestJS', level: 'strong' },
      { name: 'REST API design', level: 'strong' },
      { name: 'JWT & role-based auth', level: 'strong' },
      { name: 'DTO validation', level: 'strong' },
    ],
  },
  {
    id: 'data',
    title: 'Databases',
    icon: 'database',
    emphasis: 'secondary',
    caption: 'Schemas I design, policies I write, queries I then tune.',
    skills: [
      { name: 'PostgreSQL', level: 'production' },
      { name: 'SQL', level: 'strong' },
      { name: 'Relational schema design', level: 'strong' },
      { name: 'Row-level security', level: 'strong' },
      { name: 'Migrations', level: 'strong' },
      { name: 'Joins & Indexing', level: 'strong' },
      { name: 'Full-text search', level: 'strong' },
      { name: 'MySQL', level: 'strong' },
      { name: 'Query optimisation', level: 'working' },
      { name: 'MS SQL / T-SQL', level: 'familiar' },
    ],
  },
  {
    id: 'architecture',
    title: 'Architecture & Testing',
    icon: 'shield',
    emphasis: 'secondary',
    caption: 'What keeps a codebase readable past its first month.',
    skills: [
      { name: 'Code review', level: 'production' },
      { name: 'OOP principles', level: 'strong' },
      { name: 'SOLID', level: 'strong' },
      { name: 'Modular structure', level: 'strong' },
      { name: 'Unit testing', level: 'strong' },
      { name: 'Vitest', level: 'strong' },
      { name: 'Design patterns', level: 'working' },
      { name: 'Angular TestBed', level: 'working' },
    ],
  },
  {
    id: 'also',
    title: 'Beyond Angular',
    icon: 'sparkles',
    emphasis: 'secondary',
    caption: 'Two products shipped in Next.js — one for a client, one entirely my own.',
    skills: [
      { name: 'React', level: 'production' },
      { name: 'Next.js', level: 'production' },
      { name: 'SSR / SSG / ISR', level: 'production' },
      { name: 'Supabase', level: 'strong' },
      { name: 'Zod', level: 'strong' },
      { name: 'Android Studio', level: 'familiar' },
      { name: 'Xcode', level: 'familiar' },
    ],
  },
  {
    id: 'workflow',
    title: 'Tools & Workflow',
    icon: 'users',
    emphasis: 'secondary',
    caption: 'How the work actually reaches production.',
    skills: [
      { name: 'Git feature-branch flow', level: 'production' },
      { name: 'Pull-request review', level: 'production' },
      { name: 'Agile teamwork', level: 'production' },
      { name: 'Figma / Zeplin hand-off', level: 'production' },
      { name: 'Internationalisation (i18n)', level: 'production' },
      { name: 'npm / yarn', level: 'production' },
      { name: 'WebStorm / VS Code', level: 'production' },
    ],
  },
];
